version: "3"

services:
  api-heartee:
    container_name: api-heartee
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: dev
    depends_on:
      - pg_api_db
    restart: always
    networks:
      - my-network

  pg_api_db:
    image: postgres:bullseye
    container_name: heartee-api-db
    ports:
      - "5432:5432"
    volumes:
      - pg_data_api:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: devpass
      POSTGRES_DB: api-heartee
    restart: always
    networks:
      - my-network

volumes:
  pg_data_api:

networks:
  my-network: