spring:
  profiles:
    active: local # default
    include:
      - db
      - log

---
spring:
  datasource:
    url: jdbc:postgresql://localhost:1234/api-heartee
    username: admin
    password: localpass
    driver-class-name: org.postgresql.Driver

value:
  member-id:
    temp: 4 # JWT 기능 개발 전 토큰의 memberId 값 특정을 위해 임시로 사용