spring:
  profiles:
    include:
      - db

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB