jwt:
  secretKey: { secretKey }
  access:
    expiration: { expiration }
    header: Authorization
  refresh:
    expiration: { expiration }
    header: Authorization-refresh
  group:
    name: { name }