spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/{database-name}
    username: {username}
    password: {password}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 100
  #    open-in-view: false
