spring:
  profiles:
    include:
      - db

logging:
  file:
    path: ./logs
    max-size: 500MB
    max-history: 10
  level:
    root: info
    paibridge.apiheartee: debug
    org.hibernate.SQL: info
    org.hibernate.type: info
