spring:
  profiles:
    include:
      - db

<<<<<<< HEAD
  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type: trace
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
=======
logging:
  file:
    path: ./logs
    max-size: 500MB
    max-history: 10
  level:
    root: info
    paibridge.apiheartee: debug
    org.hibernate.SQL: info
    org.hibernate.type: info
>>>>>>> origin/dev
